### ISSUE TITLE
Make this website responsive

### ISSUE THREAD

**Issue by AbhilashaGupta16** [AbhilashaGupta16/Tic-Tac-Toe-Game#1]

**Comment by tranjenny** [comment]
I take this one

**Comment by amohapatra123** [comment]
i have made the site responsive ,you can check it at #2  .
![screencapture-file-E-opensourcecontribution-tic-tac-toe-game-TicTacToe-index-html-2020-10-12-00_22_33](https://user-images.githubusercontent.com/51486348/95687499-87feaa00-0c21-11eb-97a1-f0ccfe325ee5.png)
